### ISSUE TITLE
Support EL in Config value

### ISSUE THREAD

**Issue by hantsy** [jakartaee/config#248] opened 2024-05-03 00:57 UTC
For example, in a config properties file, we could use EL as partial value of config property.

```properties
a.name=hello
b.name=#{a.name} world // or ${a.name} world

```

**Comment by radcortez** [comment] 2024-05-03 10:24
Yes. I think we all agreed that we want to support some expression replacement mechanism.

I don't know if it should be EL or something else. Probably, EL has a lot of things that do not make sense in this context, so we need to have a proper discussion around it.

**Comment by radcortez** [comment] 2024-06-27 11:22
Duplicate of #77

**Closed by radcortez** 2024-06-27 11:22 UTC
