### ISSUE TITLE
Programmatic APIs to load config and read config 

### ISSUE THREAD

**Issue by hantsy** [jakartaee/config#141] opened 2022-11-10 15:35 UTC
Like Oracle Helidon SE, provides a simple Config to load the config by programmatic approaches.

```java
Config config=Config.create(); // provides alternative to customize the source, converters, etc.

String hostname=config.get("hostname");
int port=config.get("port");
```

**Comment by radcortez** [comment] 2024-06-27 14:18
Duplicate of https://github.com/jakartaee/config/issues/209.

**Closed by radcortez** 2024-06-27 14:18 UTC
